achiev/models.py
from django.db import models

# Create your models here.

course/models.py
from django.db import models

# Create your models here.

class ClassName(models.Model):
	name = models.CharField(max_length=200);
	date = models.DateField();

	class Meta:
		ordering = ['-date','name']

	def __str__(self):
		return self.name


class Course(models.Model):
	class_name = models.ForeignKey(ClassName,on_delete=models.CASCADE, default=1)
	date    = models.DateField(null=True, blank=True);
	title   = models.CharField(max_length=200);

	def content_file_name(instance, filename):
		return '/'.join(['course',instance.class_name.name,filename])
	handout = models.FileField(null=True, blank=True,upload_to=content_file_name);

	HANDOUT_TYPE = (
		('LC','Lecture'),
		('AP','Appendix'),
	)

	handout_type = models.CharField(
		max_length=2,
		choices=HANDOUT_TYPE,
		default='LC',
	)

	class Meta:
		ordering = ['class_name','-date']		

	def __str__(self):
		return self.title

intro/models.py
from django.db import models

# Create your models here.

link/models.py
from django.db import models

# Create your models here.
class Link(models.Model):
    english = models.CharField(max_length=30);
    chinese = models.CharField(max_length=30);
    link = models.URLField();
    img  = models.FileField(null=True, blank=True, upload_to='link_thumbnail/', default='link_thumbnail/website.png', help_text='recommended upload square image');

    def __str__(self):
        return self.english

member/models.py
from django.db import models

# Create your models here.

class JYLiu_CV(models.Model):
	cv = models.FileField(null=True, blank=True,upload_to='cv/');

	class Meta:
		verbose_name = 'JYLiu CV'
		verbose_name_plural = 'JYLiu CV'

class Member(models.Model):
	english = models.CharField(max_length=30)
	chinese = models.CharField(max_length=10)
	thumb = models.FileField(blank=True, upload_to='member_thumbnails/', default='member_thumbnails/member_thumb.png');
	IDENTITY = (
		('PD','Postdoctoral'),
		('FA','Full-time Assistant'),
		('PS','PhD Student'),
		('MS','Master Studnet'),
	)
	identity = models.CharField(
		max_length=2,
		choices=IDENTITY,
		default='PD',
	)

	email  = models.EmailField(max_length=100)

	class Meta:
		ordering = ['english']

	def __str__(self):
		return self.english


class Past(models.Model):
	english = models.CharField(max_length=30)
	chinese = models.CharField(max_length=10)
	nation  = models.CharField(max_length=15)
	start   = models.DateField()
	end	  = models.DateField()

	IDENTITY = (
		('VP','Visiting Proffesor'),
		('PD','Postdoctoral'),
	)

	identity = models.CharField(
		max_length=2,
		choices=IDENTITY,
		default='VP',
	)

	class Meta:
		ordering = ['-end']

	def __str__(self):
		return self.english

class Graduate(models.Model):
	chinese = models.CharField(max_length=10)
	start   = models.DateField()
	end	  = models.DateField()
	title	  = models.CharField(max_length=200)

	IDENTITY = (
		('PD','Philosophiæ Doctor'),
		('MD','Master'),
	)

	identity = models.CharField(
		max_length=2,
		choices=IDENTITY,
		default='PD',
	)

	class Meta:
		ordering = ['-end']

	def __str__(self):
		return self.chinese

news/models.py
from django.db import models

# Create your models here.

class News(models.Model):
	date = models.DateField();
	content = models.TextField(blank=True);
	more = models.URLField(blank=True);

	class Meta:
		verbose_name_plural = 'News'
		ordering = ['-date']

	def __str__(self):
		return self.content

research/models.py
from django.db import models

# Create your models here.

class Organization(models.Model):
	name = models.CharField(max_length=200)

	class Meta:
		ordering = ['name']
	
	def __str__(self):
		return self.name

class Research(models.Model):
	start = models.DateField()
	end   = models.DateField()
	title = models.CharField(max_length=500)
	organization = models.ForeignKey(Organization,on_delete=models.CASCADE, default=1)

	class Meta:
		verbose_name_plural = 'Researches'
		ordering = ['-start','-end']

	def __str__(self):
		return self.title

achiev/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
import os

def achiev(request):
    return render(request, 'achiev.html')

course/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rest_framework import viewsets, permissions

from .models import ClassName, Course
from .serializers import ClassNameSerializer, CourseSerializer

class ClassNameViewSet(viewsets.ModelViewSet):
    queryset = ClassName.objects.all().order_by('-id')
    serializer_class = ClassNameSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class CourseViewSet(viewsets.ModelViewSet):
    queryset = Course.objects.all().order_by('class_name')
    serializer_class = CourseSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

def course(request):
	context = {
		  'ClassNames' : ClassName.objects.all(),
#		  'Course' : Course.objects.all(),
	}

	return render(request, 'course.html', context)

intro/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
import os

def intro(request):
    return render(request, 'intro.html')

link/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rest_framework import viewsets, permissions
import os

from .models import Link
from .serializers import LinkSerializer

class LinkViewSet(viewsets.ModelViewSet):
    queryset = Link.objects.all().order_by('english')
    serializer_class = LinkSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

def link(request):
    links = Link.objects.all().order_by('english')
    return render(request, 'link.html', {'links': links})

member/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .serializers import JYLSerializer, MemberSerializer, PastSerializer, GraduateSerializer
from .models import JYLiu_CV, Member, Past, Graduate
from rest_framework import viewsets, permissions
import os

class JYLViewSet(viewsets.ModelViewSet):
    queryset = JYLiu_CV.objects.all()
    serializer_class = JYLSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class MemberViewSet(viewsets.ModelViewSet):
    queryset = Member.objects.all().order_by('-chinese')
    serializer_class = MemberSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class PastViewSet(viewsets.ModelViewSet):
    queryset = Past.objects.all()
    serializer_class = PastSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

class GraduateViewSet(viewsets.ModelViewSet):
    queryset = Graduate.objects.all()
    serializer_class = GraduateSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

def member(request):
	cv   = JYLiu_CV.objects.all()[0]
	members = Member.objects.all().order_by('english')
	pvps = Past.objects.filter(identity='VP')
	ppds = Past.objects.filter(identity='PD')
	gpds = Graduate.objects.filter(identity='PD')
	gmds = Graduate.objects.filter(identity='MD')
	context = {
		'cv'   : cv,
		'members' : members,
		'pvps' : pvps,
		'ppds' : ppds,
		'gpds' : gpds,
		'gmds' : gmds,
	}
	return render(request, 'member.html', context)

news/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
import os

from .models import News
def news(request):
    newss = News.objects.all().order_by('-date')
    context = {
        'newss' : newss
    }
    return render(request, 'news.html', context)

research/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
import os

from .models import Research

def research(request):
	context = {
		  'researches' : Research.objects.all()
	}
	return render(request, 'research.html', context)

templates/achiev.html
{% extends 'base.html'%}

{% block head_title %}
	Achievment- IRSL
{% endblock %}

{% block head_meta %}
	  <meta property="og:title" content="Achievment - IRSL"/>
	  <meta property="og:title" content="研究成果 - IRSL" />
	  <meta property="og:url" content="http://irsl.ss.ncu.edu.tw/achievement/"/>
{% endblock %}

{% block achiev_state %}
		<li class="nav-item active">
{% endblock %}

{% block banner_title%}
		Achievement
{% endblock %}

{% block body_content %}
		<div class="content-fade container mb-5">
		    <div class="row">
		        <div class="content col align-self-center text-justify">
		            <h3 class="hideme">主要研究成果說明</h3>

		            <p class="hideme">台灣位處電離層赤道異常區，因而此一研究領域為國科會規劃之重點研究方向。在國科會多年來專題計畫支持之下，主持人之研究亦由單一雷達觀測擴展為雷達、人造衛星及地磁計等之多項儀器聯合觀測鏈整體研究。而研究領域由最初之高緯度而擴展至全球電離層研究，近年來則著重在台灣地區電離層赤道異常之研究。</p>

		            <p class="hideme">最近五年主要研究成果大致可分：</p>

		            <p class="hideme">1.電離層重力波之傳播：</p>
		            <p class="hideme">引進並發展電離層重力波群速與相速之計算方法(Liu et al., JASTP, 1998)。</p>

		            <p class="hideme">2.電離層聯合觀測：</p>
		            <p class="hideme">利用特高頻和電離層雷達(Liu et al., EPS, 2002；Lee et al., JASTP, 2001a; Lee et al., ASR, 2001b)以及雷達鏈(Hsiao et al., ASR, 2001)聯合觀測電離層結構。</p>

		            <p class="hideme">3.電離層赤道異常區結構與動力：</p>
		            <p class="hideme">研究日蝕(Tsai and Liu, JGR, 1999),磁暴(Lee et al, GRL, 2002)及日、季與緯度(Tsai et al., JGR, 2001)效應。</p>

		            <p class="hideme">4.電離層赤道異常區不規則體：</p>
		            <p class="hideme">探討不同雷達及人造衛星無線電波段觀測之不規則體結構及變化(Lee et al., GRL, 2000；Shan et al., EPS , 2002)。</p>

		            <p class="hideme">5.電離層地震前兆：</p>
		            <p class="hideme">分析1994-1999台灣地區規模六以上地震期間電離層最大電子濃度之變化。結果顯示地震前五天之某一天於中午至黃昏時段，電子濃度會大量減少(Liu et al., GRL, 2000a)。由於地震前兆一直缺少強而有利之證據(Liu et al., GRL, 2000a)，是為自有電離層探測七十餘年以來第一篇探討地震電離層時間前兆－地震可能發生之時間，之學術期篇論文。事實上1998瑞里、1999集集、1999嘉義地震皆出現相類似之前兆(Chuo et al., J. Geodynamic, 2002; Chuo et al., IWSE, 2001a；; Chuo et al., ASR, 2001b; Liu et al., IWSE, 2001a)。</p>
			<p class="hideme">除此之外，申請人更利用台灣全球定位系統接收機網資料，發展經緯二維電離層全電子含量照相，並成功的觀測到921集集大地震之空間前兆－地震之可能之震央位置(Liu et al., IWSE, 2001a; Liu et al., GRL, 2001b)。兩篇論文(Liu et al., GRL, 2000a；2001b)是目前地震預警研究電離層地震之時間及空間前兆研究的首次證據及重要成果(參見劉正彥, 科學發展, 2002)。</p>
		        </div>
		    </div>
		</div>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
    <head>
        <title>
          	{% block head_title %}
          	{% endblock %}
        </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head_meta %}
        {% endblock %}
        <meta property="og:image" content='{% static "images/irsl_h_b.png" %}'/>
        <meta property="og:description" content="歡迎來到太空科學研究所電離層物理實驗室，希望藉此網頁能夠讓更多的人認識我們並讓更多的人認識電離層物理，如果對電離層物理有興趣或有任何疑問，歡迎與我們聯絡。" />
        <meta property="og:description" content="Welcome to the website of ionospheric physics laboratory, NCU. It is our pleasure to make more people to understand and appreciate about the Ionospheric Physics. If you have any questions abous our work, feel free to contact us."/>
        <meta property="og:locale" content="zh_TW" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="IRSL" />
        <link rel="icon" href='{% static "images/irsl_icon.png" %}' />
        <link rel="stylesheet" type="text/css" href='{% static "css/cover_h.css" %}'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
        <link rel="stylesheet" href='{% static "css/hamburgers.css" %}' type="text/css">
        <link rel="stylesheet" href='{% static "css/style.css" %}' type="text/css">
        <link rel="stylesheet" type="text/css" href='{% static "css/bounce_arrow.css" %}'>
        {% block stylesheet %}
        {% endblock %}
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" ></script>
        <script src='{% static "js/jquery.waypoints.min.js" %}' type="text/javascript"></script>
        <script src='{% static "js/style.js" %}' type="text/javascript"></script>
        <script src='{% static "js/animate.js" %}' type="text/javascript"></script>
    </head>

    <body>
        {% block nav %}
            <nav class="header-fade navbar fixed-top navbar-toggleable-md navbar-light bg-faded">
                <div class="container">
                    <a class="navbar-brand mb-0" href="{% url 'home' %}">
                        <img class='navbar-logo' src='{% static "images/irsl_h_b.png" %}'>
                    </a>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav ml-auto">
                            {% block intro_state %}<li class="nav-item">{% endblock %} <a class="nav-link" href="{% url 'intro' %}">Introduction </a></li>
                            {% block news_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'news' %}">News </a></li>
                            {% block member_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'member' %}">Member </a></li>
                            {% block course_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'course' %}">Course </a></li>
                            {% block pub_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'pub' %}">Publication </a></li>
                            {% block achiev_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'achiev' %}">Achievement </a></li>
                            {% block conf_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'conf' %}">Conference </a></li>
                            {% block research_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'research' %}">Research </a></li>
                            {% block link_state %}<li class="nav-item">{% endblock %}<a class="nav-link" href="{% url 'link' %}">Link </a></li>
                        </ul>
                    </div>
                </div>
                <button class="navbar-toggler navbar-toggler-right hamburger-light hamburger hamburger--animate" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </nav>
        {% endblock %}

        {% block body_banner %}
            <div class="header-fade header jumbotron">
                <h2 class="header-h2-fade">{% block banner_title%}{% endblock %}</h2>
            </div>
        {% endblock%}

        {% block body_content %}
        {% endblock %}

        {% block body_footer %}
            <footer class="footer-fade footer">
                <div class="container text-center">
                    <br>
                    <span class="text-muted">
                        地址：32001 桃園市中壢區中大路300號科學四館803-1室
                        <br>
                        Add：Room 803-1 Science Buildin 4, No. 300, Zhongda Rd., Zhongli District, Taoyuan City 32001, Taiwan
                        <br>
                        TEL：886-3-4227151 Ext.65780
                        <br>
                        E-Mail：jyliu@jupiter.ss.ncu.edu.tw
                        <br>
                        Copyright © 2017 Yi-Wei Chang. All rights reserved.
                        <br>
                    </span>
                </div>
            </footer>
        {% endblock %}

        {% block foot_js %}
            <script src='{% static "js/animate.js" %}' type="text/javascript"></script>
        {% endblock %}
    </body>
</html>

templates/conf.html
{% extends 'base.html' %}

{% block head_title %}
      Conference - IRSL
{% endblock %}	  
       
{% block head_meta %}	  
      <meta property="og:title" content="Conference - IRSL"/>
      <meta property="og:title" content="參與會議 - IRSL" />
      <meta property="og:url" content="http://irsl.ss.ncu.edu.tw/conference/"/>
{% endblock %}

{% block conf_state %}
	<li class="nav-item active">
{% endblock %}
            
{% block banner_title %}		
	Conference
{% endblock %}
        
{% block body_content %}
        <div class="content-fade container conf mb-5">
            <div class="row">
                <div class="content col align-self-center text-justify hidden-sm-down">
                    <h3>協辦研討會</h3>
                    <table>
			  {% for conf in confs %}
                        <tr class="hideme"><td class="con-td1">{{conf.start}}~{{conf.end}}</td>
                            <td class="con-td2">{{conf.title}}</td>
                            <td class="con-td3">{{conf.location}}</td></tr>
			  {% endfor %}
                    </table> 
                    <br>
                    <h3>受邀演講</h3>
                    <table>
			  {% for oral in orals %}
                        <tr class="hideme"><td class="con-td1">{{oral.date}}</td>
                            <td class="con-td2">{{oral.title}}</td>
                            <td class="con-td3">{{oral.location}}</td></tr>
			  {% endfor %}
                    </table>          
                </div>                           
                <div class="content col align-self-center text-center hidden-md-up">
                    <h3>協辦研討會</h3>
                    <table class="text-center">
			  {% for conf in confs %}
                        <tr class="hideme"><td>{{conf.start}}~{{conf.end}}<br>
                            			     {{conf.title}}<br>
                            			     {{conf.location}}</td></tr>
			  {% endfor %}
                    </table>           
                    <br>
                    <h3>受邀演講</h3>
			  {% for oral in orals %}
                        <tr class="hideme"><td>{{oral.date}}<br>
                            			     {{oral.title}}<br>
                            			     {{oral.location}}</td></tr>
			  {% endfor %}
                    </table>
                    <br>                    
                </div>
            </div>            
        </div>
{% endblock %}	  

templates/member.html
{% extends 'base.html' %}

{% block head_title %}
	Member - IRSL
{% endblock %}

{% block head_meta %}
        <meta property="og:title" content="Member - IRSL"/>
        <meta property="og:title" content="實驗室成員 - IRSL" />
        <meta property="og:url" content="http://www.ss.ncu.edu.tw/~jyliu/news.html" />
				<style>
                        .members{                            
                            display: grid;
                            grid-template-columns: 1fr 1fr 1fr 1fr;
                            grid-auto-flow: row;
                            -ms-grid-columns: 1fr 1fr 1fr 1fr;
                        }
                        .members .profile-card{
                            display:inline-block;
                            width: 20%\0;
                        }
                        @media only screen and (max-width : 991px) {
							.members{
                                display: -ms-grid;
                                display: grid;
                                grid-template-columns: 1fr 1fr 1fr;
                                -ms-grid-column: 1fr 1fr 1fr;
                            }
                        }
                        @media only screen and (max-width : 700px) {
							.members{
                                display: -ms-grid;
                                display: grid;
                                grid-template-columns: 1fr 1fr;
                                -ms-grid-column: 1fr 1fr;
                            }
						}  
                        @media only screen and (max-width : 580px) {
							.members{
                                display: -ms-grid;
                                display: grid;
                                grid-template-columns: 1fr;
                                -ms-grid-column: 1fr;
                            }
						}                        
				</style>
{% endblock %}

{% block member_state %}
				<li class="nav-item active">
{% endblock %}

{% block banner_title %}
	Member
{% endblock %}

{% block body_content %}
        <div class="content-fade container member pt-3 mb-5">
            <div class="hideme jyliu yliu row hidden-md-down">
                <div class="col-lg-4 col-md-12 align-self-left pb-5">
                    <img src="/static/images/jyliu.png" width=270px>
                </div>
                <div class="col-auto align-self-left pb-5">
                    <h4> 劉正彥(JANN-YENQ TIGER LIU) </h4>
                    <p> PhD, Physics Dept, Utah State University </p>
                    <p> Ionospheric Physics  </p>
                    <p> Room 816 (8th floor), Science Building 4, NCU   </p>
                    <p> (03)4227151~65763  </p>
                    <p> <a href="mailto:jyliu@jupiter.ss.ncu.edu.tw">jyliu@jupiter.ss.ncu.edu.tw</a>  </p>
                    <p> <a href={{cv.cv.url}} target="_blank">Curriculum Vitae</a></p>
                </div>
            </div>
            <div class="hideme jyliu row hidden-lg-up text-center">
                <div class="col pb-5">
                    <h4> 劉正彥(JANN-YENQ TIGER LIU) </h4>
                    <br>
                    <img src="/static/images/jyliu.png" width=270px>
                </div>
            </div>
            <div class="jyliu row hidden-lg-up text-center">
                <div class="col pb-5">
                    <p> PhD, Physics Dept, Utah State University </p>
                    <p> Ionospheric Physics  </p>
                    <p> Room 816 (8th floor), Science Building 4, NCU   </p>
                    <p> (03)4227151~65763  </p>
                    <p> <a href="mailto:jyliu@jupiter.ss.ncu.edu.tw">jyliu@jupiter.ss.ncu.edu.tw</a>  </p>
                    <p> <a href="doc/20150721_MOST_105%20CV_final_jyl.doc" target="_blank">Curriculum Vitae</a></p>
                </div>
            </div>
            <br><br>
            <div class="members text-center">
                {% for mi in members %}
                    <div class="profile-card hideme text-center mx-auto mb-4">
                        <img class="rounded-circle mx-auto" src="/media/{{mi.thumb}}" style="height: 150px ;width: 150px; object-fit: cover;">
                        <div class="py-3">
                            <h5 class="py-0">{{mi.english}}</h5>
                            <h5 class="py-0">{{mi.chinese}}</h5>
                            <p class="py-0">{{mi.get_identity_display}}</p>
                            <p class="py-0">{{mi.email}}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <br><br>
            <div class="hideme vp row hidden-sm-down">
                <div class="col align-self-left">
                    <h4>歷年客座教授(Visiting Proffesor)</h4>
                    <table class="PhD_table">
			  	{% for pvp in pvps %}
                        <tr class="hideme"><td class="PhD_name">Dr. {{pvp.english}} {{pvp.chinese}} </td>
                            <td class="PhD_country">{{pvp.nation}}</td>
                            <td>{{pvp.start}}~{{pvp.end}}</td></tr>
			  	{% endfor %}
                    </table>
                    <br>
                </div>
            </div>
            <div class="hideme pd row hidden-sm-down">
                <div class="col align-self-left">
                    <h4>歷年博士後研究(Postdoctoral) </h4>
                    <table class="PhD_table">
			  	{% for ppd in ppds %}
                        <tr class="hideme"><td class="PhD_name">Dr. {{ppd.english}} {{ppd.chinese}} </td>
                            <td class="PhD_country">{{ppd.nation}}</td>
                            <td>{{ppd.start}}~{{ppd.end}}</td></tr>
			  	{% endfor %}
                    </table>
			  <br>
                </div>
            </div>
            <div class="st row hidden-sm-down">
                <div class="col align-self-left">
                    <h4 class="hideme">歷年畢業學生(Graduate Student)</h4>
                    <br>
                    <h5 class="hideme">博士 Doctor</h5>
                    <table class="hideme graduate_table">
			  	{% for gpd in gpds %}
				<tr class="hideme"><td class="graduate_name"> {{gpd.chinese}} </td>
                            <td class="graduate_year"> {{gpd.start}}~{{gpd.end}} </td>
                            <td> {{gpd.title}} </td></tr>
			  	{% endfor %}
                    </table>
                    <br>
                    <h5 class="hideme">碩士 Master</h5>
                    <table class="hideme graduate_table">
			  	{% for gmd in gmds %}
				<tr class="hideme"><td class="graduate_name"> {{gmd.chinese}} </td>
                            <td class="graduate_year"> {{gmd.start}}~{{gmd.end}} </td>
                            <td> {{gmd.title}} </td></tr>
			  	{% endfor %}
                    </table>
                </div>
            </div>

            <div class="hideme vp row text-center hidden-md-up">
                <div class="col align-self-left">
                    <h4>歷年客座教授(Visiting Proffesor)</h4>
                    <table class="PhD_table text-center">
			  	{% for pvp in pvps %}
                        <tr class="hideme"><td class="PhD_name">Dr. {{pvp.english}} {{pvp.chinese}} <br>
                            {{pvp.nation}} <br>
                            {{pvp.start}}~{{pvp.end}} <br></tr>
			  	{% endfor %}
                    </table>
                    <br>
                </div>
            </div>
            <div class="hideme pd row text-center hidden-md-up">
                <div class="col align-self-left">
                    <h4>歷年博士後研究(Postdoctoral) </h4>
                    <table class="PhD_table text-center">
			  	{% for ppd in ppds %}
                        <tr class="hideme"><td class="PhD_name">Dr. {{ppd.english}} {{ppd.chinese}} <br>
                            {{ppd.nation}} <br>
                            {{ppd.start}}~{{ppd.end}} <br></tr>
			  	{% endfor %}
                    </table>
			  <br>
                </div>
            </div>
            <div class="st row text-center hidden-md-up">
                <div class="col align-self-left">
                    <h4 class="hideme">歷年畢業學生(Graduate Student)</h4>

                    <br>
                    <h5 class="hideme">博士 Doctor</h5>
                    <table class="hideme graduate_table text-center">
			  	{% for gpd in gpds %}
				<tr class="hideme"><td class="graduate_name"> {{gpd.chinese}} <br>
                            {{gpd.start}}~{{gpd.end}} <br>
                            {{gpd.title}} <br></tr>
			  	{% endfor %}
                    </table>
                    <br>
                    <h5 class="hideme">碩士 Master</h5>
                    <table class="hideme graduate_table text-center">
			  	{% for gmd in gmds %}
				<tr class="hideme"><td class="graduate_name"> {{gmd.chinese}} <br>
                            {{gmd.start}}~{{gmd.end}} <br>
                            {{gmd.title}} <br></tr>
			  	{% endfor %}
                    </table>
                </div>
            </div>
        </div>
{% endblock %}